version: '3.9'
services:
  app:
    image: byancode/galera-manager
    depends_on:
      - influxdb
    restart: unless-stopped
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=12345
      - INFLUXDB_URL=http://gmd:12345@1.2.3.4:8086
    volumes:
      - ./data/configs:/var/lib/gmd:rw
      - ./data/logs:/var/log/gmd:rw
    networks:
      - backend

  influxdb:
    image: influxdb:1.8
    restart: unless-stopped
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=gmd
      - INFLUXDB_ADMIN_PASSWORD=12345
      - INFLUXDB_DB=gmd
    volumes:
      - ./data/influxdb:/var/lib/influxdb:rw
    networks:
      - backend

networks:
  backend: